# Generated by Django 2.1.7 on 2019-04-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0004_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, to='asker.Answers'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='asker.Tag'),
        ),
    ]
