# Generated by Django 2.1.7 on 2019-04-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0006_auto_20190415_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asker.Answers'),
        ),
    ]
