# Generated by Django 2.1.7 on 2019-04-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0008_auto_20190423_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(default=1, null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='asker.Question'),
            preserve_default=False,
        ),
    ]
