# Generated by Django 2.1.7 on 2019-04-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0009_auto_20190423_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asker.Question'),
            preserve_default=False,
        ),
    ]
