# Generated by Django 2.1.7 on 2019-04-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0010_auto_20190423_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asker.Question'),
        ),
    ]
